name: "buf-breaking"
description: >
  Check that the Input location has no breaking changes compared to the "against" location.
branding:
  icon: alert-triangle
  color: blue
inputs:
  # For more on Buf Inputs:
  # https://docs.buf.build/inputs#specifying-an-input
  input:
    description: "The Input path. Defaults to the root of the current repository."
    required: false
    default: "."
  # For more on "against" in breaking change detection:
  # https://docs.buf.build/breaking/usage#run-breaking-change-detection
  against:
    description: "The Input to check compatibility against."
    required: true
  buf_input_https_username:
    description: "The username for the repository to check compatibility against."
    required: false
    default: ${{ github.actor }}
  buf_input_https_password:
    description: "The password for the repository to check compatibility against."
    required: false
    default: ${{ github.token }}
  buf_token:
    description: "The buf authentication token used for private inputs."
    required: false
runs:
  using: "node16"
  main: "./dist/main.js"
