name: 'buf-breaking'
description: >
  Check that the input location has no breaking changes compared to the against location.
branding:
  icon: alert-triangle
  color: blue
inputs:
  # The definition of an input can be found in the following:
  # https://docs.buf.build/inputs#specifying-an-input
  input:
    description: 'The input path.'
    required: true
    default: '.'
  # The definition of an against input can be found in the following:
  # https://docs.buf.build/inputs#specifying-an-input
  against:
    description: 'The reference to check compatibility against.'
    required: true
  # The Github token MUST be referenced in the workflow file.
  # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
  github_token:
    description: 'The Github authentication token.'
    required: true
  buf_token:
    description: 'The buf authentication token used for private inputs.'
runs:
  using: 'node12'
  main: './dist/main.js'
