name: 'buf-breaking'
description: >
  Check that the input location has no breaking changes compared to the against location.
branding:
  icon: alert-triangle
  color: blue
inputs:
  # The definition of an input can be found in the following:
  # https://docs.buf.build/inputs#specifying-an-input
  input:
    description: 'The input path.'
    required: false
  # The definition of an against input can be found in the following:
  # https://docs.buf.build/inputs#specifying-an-input
  against:
    description: 'The reference to check compatibility against.'
    required: true
  buf_input_https_username:
    description: 'The username for the repository to check compatibility against.'
    default: ${{ github.actor }}
  buf_input_https_password:
    description: 'The password for the repository to check compatibility against.'
    default: ${{ github.token }}
  buf_token:
    description: 'The buf authentication token used for private inputs.'
runs:
  using: 'node12'
  main: './dist/main.js'
