# Apply to all pull requests
on: pull_request
jobs:
  validate-protos:
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v2
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v0.5.0
      # Perform breaking change detection against the `proto` directory in the `main` branch
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'proto'
          against: 'https://github.com/acme/weather.git#branch=main,ref=HEAD~1,subdir=proto'
